# Generated by Django 4.2.5 on 2023-09-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
